# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('shapeType', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrisisCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('crisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Crisis')),
            ],
        ),
    ]
