# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20161105_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='dispatcher',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='agency',
            field=models.CharField(default='Police', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatch',
            name='contact',
            field=models.IntegerField(default=91007606, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatch',
            name='resource',
            field=models.CharField(default='4 police cars', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatch',
            name='time',
            field=models.CharField(default='time', max_length=50),
            preserve_default=False,
        ),
    ]
